- platform: mqtt
  name: socket1
  state_topic: "socket/1"
  command_topic: "socket/1/set"
  retain: true
  optimistic: true
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0

- platform: mqtt
  name: hyperion
  state_topic: "home/hyperion"
  command_topic: "home/hyperion/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
  value_template: '{{ value_json.value }}'
