- platform: mqtt
  state_topic: 'home/livingroom/humidity'
  name: 'livingroom_sensor_humidity'
  qos: 0
  unit_of_measurement: '%'
  value_template: '{{ value_json.current }}'

- platform: mqtt
  state_topic: 'home/livingroom/temperature'
  name: 'livingroom_sensor_temperature'
  qos: 0
  unit_of_measurement: °C
  value_template: '{{ value_json.current }}'

- platform: mqtt
  state_topic: 'home/bedroom/humidity'
  name: 'bedroom_sensor_humidity'
  qos: 0
  unit_of_measurement: '%'
  value_template: '{{ value_json.current }}'

- platform: mqtt
  state_topic: 'home/bedroom/temperature'
  name: 'bedroom_sensor_temperature'
  qos: 0
  unit_of_measurement: °C
  value_template: '{{ value_json.current }}'
